language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

compiler: 
  - gcc
  - clang

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
    - libboost-all-dev

script:
  - mkdir build && cd build && cmake .. && cmake --build . --target install

